import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from '../utils/cn';
import { PriceDisplay } from './PriceDisplay';
import { RatingStars } from './RatingStars';
import { Badge } from './Badge';
export function ProductCard({ product, onClick, className }) {
    const primaryImage = product.images?.find((img) => img.isPrimary) ?? product.images?.[0];
    const isOutOfStock = product.available <= 0;
    return (_jsxs("div", { onClick: onClick, className: cn('bg-card border-border group relative overflow-hidden rounded-xl border transition-all duration-200', onClick && 'hover:shadow-card cursor-pointer hover:-translate-y-0.5', className), children: [_jsxs("div", { className: "bg-muted relative aspect-square overflow-hidden", children: [primaryImage ? (_jsx("img", { src: primaryImage.url, alt: primaryImage.alt ?? product.name, className: "h-full w-full object-cover transition-transform duration-300 group-hover:scale-105", loading: "lazy" })) : (_jsx("div", { className: "flex h-full items-center justify-center", children: _jsx("span", { className: "text-muted-foreground text-sm", children: "No image" }) })), _jsxs("div", { className: "absolute left-2 top-2 flex flex-col gap-1", children: [product.comparePrice != null && product.comparePrice > product.price && (_jsx(Badge, { variant: "danger", children: "Sale" })), isOutOfStock && _jsx(Badge, { variant: "default", children: "Out of stock" })] })] }), _jsxs("div", { className: "flex flex-col gap-2 p-4", children: [product.species && (_jsx("span", { className: "text-muted-foreground text-xs uppercase tracking-wide", children: product.species.name })), _jsx("h3", { className: "text-foreground line-clamp-2 text-sm font-semibold leading-snug", children: product.name }), product.reviewCount > 0 && (_jsx(RatingStars, { value: product.avgRating, size: "sm", count: product.reviewCount })), _jsx(PriceDisplay, { price: product.price, comparePrice: product.comparePrice, size: "sm" }), !isOutOfStock && product.available <= 5 && (_jsxs("span", { className: "text-warning text-xs", children: ["Only ", product.available, " left"] }))] })] }));
}
