import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Helmet } from 'react-helmet-async';
import { Link, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@repo/ui';
export default function OrderSuccessPage() {
    const location = useLocation();
    const orderId = location.state?.orderId;
    return (_jsxs(_Fragment, { children: [_jsxs(Helmet, { children: [_jsx("title", { children: "Order Successful \u2013 AquaLuxe" }), _jsx("meta", { name: "robots", content: "noindex" })] }), _jsx("div", { className: "mx-auto flex min-h-[60vh] max-w-[1280px] items-center justify-center px-4 py-16 md:px-10", children: _jsxs(motion.div, { className: "text-center", initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: [_jsx(motion.div, { className: "mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-emerald-500/10", initial: { scale: 0 }, animate: { scale: 1 }, transition: { type: 'spring', stiffness: 200, delay: 0.2 }, children: _jsx(motion.svg, { className: "h-10 w-10 text-emerald-500", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2.5, initial: { pathLength: 0 }, animate: { pathLength: 1 }, transition: { duration: 0.4, delay: 0.5 }, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M5 13l4 4L19 7" }) }) }), _jsx("h1", { className: "text-foreground text-3xl font-bold", children: "Order Placed Successfully!" }), _jsx("p", { className: "text-muted-foreground mt-3 text-lg", children: "Thank you for shopping at AquaLuxe. We'll take great care of your new aquatic friends!" }), orderId && (_jsxs(motion.div, { className: "bg-card border-border shadow-card mx-auto mt-8 max-w-sm rounded-2xl border p-6", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.6 }, children: [_jsx("p", { className: "text-muted-foreground mb-1 text-sm", children: "Order ID" }), _jsx("p", { className: "text-foreground break-all font-mono text-sm font-semibold", children: orderId }), _jsx(Link, { to: `/orders/${orderId}`, children: _jsx(Button, { variant: "outline", size: "sm", className: "mt-4 w-full", children: "View Order Details" }) })] })), _jsxs("div", { className: "mt-8 flex flex-wrap items-center justify-center gap-4", children: [_jsx(Link, { to: "/orders", children: _jsx(Button, { variant: "outline", children: "My Orders" }) }), _jsx(Link, { to: "/products", children: _jsx(Button, { children: "Continue Shopping" }) })] }), _jsx(motion.div, { className: "mt-12 text-5xl", animate: { x: [0, 10, -10, 0] }, transition: { duration: 3, repeat: Infinity, ease: 'easeInOut' }, children: "\uD83D\uDC20" })] }) })] }));
}
